name: "Android Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release APK
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '23.0.1'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/*.apk
          tag: v1.0.${{ .github.run_number }}
          token: ${{ secrets.TOKEN }}